openapi: 3.0.3
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    version: '1.0.0'
    termsOfService: 'http://swagger.io/terms/'
servers:
    - url: http://localhost:3001/api/v1
paths:
    /user/login:
        post:
            tags:
                - User Module
            summary: Login
            description: API for Login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Login'
            responses:
                '200':
                    description: Login Successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/signup:
        post:
            tags:
                - User Module
            summary: Signup
            description: API for Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
            responses:
                '200':
                    description: Signup Successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/profile:
        post:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for fetching a user profile
            responses:
                '200':
                    description: User profile retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for updating a user profile
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserProfile'
            responses:
                '200':
                    description: User profile updated successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /user/account:
        get:
            security:
                - Bearer: []
            tags:
                - Money Module
            summary: Get User Profile Transactions
            description: API for retrieving transactions associated with the user's profile
            parameters:
                - in: query
                  name: UserID
                  description: ID of the user
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Transactions retrieved successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TransactionsResponse'
                '400':
                    description: Invalid Fields or Incorrect UserID
                '500':
                    description: Internal Server Error
    /user/account/description:
        put:
            security:
                - Bearer: []
            tags:
                - Money Module
            summary: Update Account Description
            description: API for updating the description of a user's account
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateAccountDescription'
            responses:
                '200':
                    description: Account description updated successfully
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error

components:
    securitySchemes:
        Bearer:
            type: apiKey
            name: Authorization
            in: header
    schemas:
        User:
            type: object
            properties:
                email:
                    type: string
                    description: user email
                password:
                    type: string
                    description: user password
                firstName:
                    type: string
                    description: user first name
                lastName:
                    type: string
                    description: user last name
                userName:
                    type: string
                    description: user public name
        Login:
            type: object
            properties:
                email:
                    type: string
                    description: user email
                password:
                    type: string
                    description: user password
        ApiResponse:
            type: object
            properties:
                status:
                    type: integer
                message:
                    type: string
                body:
                    type: object
                    properties:
                        id:
                            type: string
                        email:
                            type: string
        LoginResponse:
            type: object
            properties:
                token:
                    type: string
        UserProfile:
            type: object
            properties:
                userName:
                    type: string
        TransactionsResponse:
            type: object
            properties:
                transactions:
                    type: array
                    items:
                        $ref: '#/components/schemas/Transaction'
        Transaction:
            type: object
            properties:
                transactionId:
                    type: string
                accountId:
                    type: string
                amount:
                    type: number
                date:
                    type: string
                    format: date-time
                description:
                    type: string
                category:
                    type: string
        UpdateAccountDescription:
            type: object
            properties:
                description:
                    type: string
                    description: New description for the account
